遗传算法实践——OneMax问题

In [2]:
from deap import base
from deap import creator,tools
import random
import matplotlib.pyplot as plt

In [3]:
#超参数声明
ONE_MAX_LENGTH = 100    #length of bit string to be optimized
POPULATION_SIZE = 200   #number of individuals in population
P_CROSSOVER = 0.9       #probability for crossover
P_MUTATION = 0.1        #probability for mutating an individual
MAX_GENERATION = 50     #max number of generations for stopping condition


In [4]:
toolbox = base.Toolbox()
toolbox.register("zeroOrOne",random.randint,0,1)

creator.create("FitnessMax",base.Fitness,weights=(1.0,))

In [5]:
creator.create("Individual",list,fitness=creator.FitnessMax)
toolbox.register("IndividualCreator",tools.initRepeat,creator.Individual,toolbox.zeroOrOne,ONE_MAX_LENGTH)

In [6]:
toolbox.register("populationCreator",tools.initRepeat,list,toolbox.IndividualCreator)


In [7]:
def oneMaxFitness(individual):
    return sum(individual),#deap中的适用度表示为元组，因此，当返回单个值时，需要用逗号将其声明为元组。
toolbox.register("evaluate",oneMaxFitness)


In [8]:
toolbox.register("select",tools.selTournament,tournsize=3)
toolbox.register("mate",tools.cxOnePoint)
# mutFlipBit函数遍历个体的所有特征，并且对于每个特征值，
# 都将使用indpb参数值作为翻转（应用not运算符）该特征值的概率。
# 该值与突变概率无关，后者由P_MUTATION常数设置。
# 突变概率用于确定是否为种群中的给定个体调用mutFlipBit函数
toolbox.register("mutate",tools.mutFlipBit,indpb=1.0/ONE_MAX_LENGTH)


In [9]:
def main():
    population = toolbox.populationCreator(n=POPULATION_SIZE)
    generationCounter = 0
    fitnessValues = list(map(toolbox.evaluate,population))

    for individual,fitnessValue in zip(population,fitnessValues):
        individual.fitness.values = fitnessValue

    fitnessValues = [individual.fitness.values[0] for individual in population]

    maxFitnessValues = []
    meanFitnessValues = []

    while max(fitnessValues) < ONE_MAX_LENGTH and generationCounter < MAX_GENERATION:
        generationCounter = generationCounter + 1
        
        offspring = toolbox.select(population,len(population))
        offspring = list(map(toolbox.clone,offspring))

        for child1,child2 in zip(offspring[::2],offspring[1::2]):
            if random.random() < P_CROSSOVER:
                toolbox.mate(child1,child2)
                del child1.fitness.values
                del child2.fitness.values
        
        for mutant in offspring:
            if random.random() < P_MUTATION:
                toolbox.mutate(mutant)
                del mutant.fitness.values
        
        freshIndividuals = [ind for ind in offspring if not ind.fitness.valid]
        freshFitnessValues = list(map(toolbox.evaluate,freshIndividuals))
        for individual,fitnessValue in zip(freshIndividuals,freshFitnessValues):
            individual.fitness.values = fitnessValue
        
        population[:] = offspring

        fitnessValues = [ind.fitness.values[0] for ind in population]

        maxFitnessValue = max(fitnessValues)
        meanFitnessValue = sum(fitnessValues) / len(population)
        maxFitnessValues.append(maxFitnessValue)
        meanFitnessValues.append(meanFitnessValue)
        print("- Generation {}: Max Fitness = {}, Avg Fitness = {}".format(generationCounter,maxFitnessValue,meanFitnessValue))

        best_index = fitnessValues.index(max(fitnessValues))
        print("Best Indivadual = ", *population[best_index],"\n")

    plt.plot(maxFitnessValues,color="red")
    plt.plot(meanFitnessValues,color="green")
    plt.xlabel("Generation")
    plt.ylabel("Max / Average Fitness")
    plt.title("Max and Average fitness over Generation")
    plt.show()


# 动手写遗传算法

In [10]:
import numpy as np
a=np.random.randint(0,50,(1,3))
inheritedIndividual = 70

In [11]:
coefficient=np.array([3,4,5])
right=100
maxSize=100
def generate(coefficient,right,maxSize):
    individual=np.array([[1,1,1]])
    while np.size(individual,0)<maxSize:
        ans=np.random.randint(0,50,(1,3))
        if np.dot(ans,coefficient)<right:
            individual=np.vstack((individual,ans))
    return individual
individual=generate(coefficient,right,maxSize)
print(individual.shape)
print(individual)

(100, 3)
[[ 1  1  1]
 [ 5  7  8]
 [ 4 18  2]
 [14  7  2]
 [ 3  8 10]
 [11  8  2]
 [ 8 11  2]
 [ 0  4  2]
 [ 3  1 15]
 [ 2  1 14]
 [10  5  7]
 [ 4  1  3]
 [15  4  2]
 [ 0 13  9]
 [ 5 12  7]
 [ 3  5 14]
 [ 6  4  0]
 [11  1  9]
 [15  7  3]
 [ 2 10  1]
 [23  0  2]
 [16  0  9]
 [ 4 19  2]
 [20  7  2]
 [ 6 16  3]
 [ 0 11  4]
 [ 1 17  2]
 [25  3  1]
 [13  0  8]
 [ 3  2 13]
 [18  0  4]
 [13  8  2]
 [ 5  7  6]
 [11 16  0]
 [16  5  1]
 [ 5 17  3]
 [ 1 17  2]
 [12  4  0]
 [10  1 12]
 [ 3 11  0]
 [20  5  2]
 [24  3  2]
 [14  1  9]
 [10  9  5]
 [ 4  8  0]
 [ 0 19  2]
 [11  7  6]
 [15  6  6]
 [28  2  1]
 [12 14  0]
 [ 0 12  3]
 [ 6  1  3]
 [14  6  2]
 [17 10  1]
 [13  3  7]
 [ 3  7 10]
 [10  6  0]
 [ 8  7  4]
 [ 5 10  2]
 [ 4 15  3]
 [ 5  4  9]
 [12 12  0]
 [ 6  3  1]
 [12 10  0]
 [ 9  5  5]
 [ 3  5 10]
 [ 6  3  0]
 [ 7  9  5]
 [22  7  1]
 [ 4  0  1]
 [10 13  1]
 [ 8  7  4]
 [ 0 16  0]
 [ 7 15  0]
 [12  0  3]
 [ 3  0  9]
 [ 3  5 13]
 [ 7  8  7]
 [ 1 14  2]
 [ 4  5 13]
 [ 9 10  0]
 [26  1  3]
 [14  3

In [12]:
# def calFitness(individuals):
#     fitness=[]
#     for ind in individuals:
#         fitness.append(sum(ind))
#     return fitness
# 
# def inheritance(individuals,sort):
#     new_individuals=[]
#     for i in range(len(individuals)):
#         if sort[i]<inheritedIndividual:
#             new_individuals.append(individuals[i])
#     return new_individuals
# 
# def variance(individuals,new_individuals):
# 
#     while np.size(new_individuals,0)<maxSize:
#         
#         i=random.randint(0,maxSize-1)
#         ind=individuals[i]
#         ind[0]=ind[0]+random.gauss(5)
#         ind[1]=ind[1]+random.gauss(3)
#         ind[2]=ind[2]+random.gauss(2)
#         ind=np.array([ind])
#         if np.dot(ind,coefficient)<right:
#             new_individuals=np.vstack((new_individuals,ind))
#     return new_individuals
#             
# fitness=calFitness(individual)
# sort=np.argsort(fitness)
# circle=1
# print(max(fitness))
# while max(fitness)<50:
#     circle=circle+1
#     new_individuals=inheritance(individual,sort)
#     new_individuals=variance(individual,new_individuals)
#     new_individuals=np.array(new_individuals)
#     fitness=calFitness(new_individuals)
#     sort=np.argsort(fitness)
#     print(f"when in circle: {circle}, the max fitness is {max(fitness)},the individuals are {new_individuals}")
#     

In [32]:
temp=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=temp[2]
b=list(b)
print(b,temp)
b[1]=111111
np.array(b)
print(b,temp)

[7, 8, 9] [[1 2 3]
 [4 5 6]
 [7 8 9]]
[7, 111111, 9] [[1 2 3]
 [4 5 6]
 [7 8 9]]
