In [9]:
import numpy as np

In [10]:
# 输入参评数目和指标数目
# n=int(input())
# m=int(input())
n=3
m=4

## 接收输入数据类型， 1，极大型 2，极小型 3，中间型 4，区间型

In [11]:
# kind=input().split(" ")
kind=[1,2,3,4]

## 接收用户输入的矩阵并转换为numpy数组

In [12]:
# A=np.zeros((n,m))
# for i in range(n):
#     A[i]=input().split(" ")
#     A[i]=list(map(float,A[i]))
A=np.array([[  9., 10.,175.,120.]
 ,[  8.,7., 164.,  80.]
 ,[  6.,   3., 157.,  90.]])
print(f"输入矩阵为{A}")

输入矩阵为[[  9.  10. 175. 120.]
 [  8.   7. 164.  80.]
 [  6.   3. 157.  90.]]


## 极小型转化为极大型

In [13]:
def minToMax(max, x):
    x=list(x)
    ans=[[(max-e)]for e in x]
    return np.array(ans)

## 中间型转化为极大型

In [14]:
def midToMax(best, x):
    x=list(x)
    h=[abs(e-best) for e in x]
    M=max(h)
    if M==0:
        return np.array(x)
    ans=[[(1-e/M)]for e in h]
    return np.array(ans)

## 区间型到极大型

In [15]:
def regToMax(low,high, x):
    x=list(x)
    M=max(low-min(x),max(x)-high)
    if M==0:
        return np.array(x)
    ans=[]
    for i in range(len(x)):
        if x[i]<low:
            ans.append([(1-(low-x[i])/M)])
        elif x[i]>high:
            ans.append([(1-(x[i]-high)/M)])
        else:
            ans.append([1])
    return np.array(ans)

# 统一指标类型

In [16]:
X=np.zeros((n,1))
for i in range(m):
    if kind[i]=="1":
        v=np.array(A[:,i])
    elif kind[i]=="2":
        v=minToMax(max(A[:,i]),A[:,i])
    elif kind[i]=="3":
        best=165 # 输入最优解
        v=midToMax(best,A[:,i])
    else:
        low=90
        high=100
        v=regToMax(low,high,A[:,i])
    if i==0:
        X=v.reshape(-1,1) # 转换为列向量
    else:
        X=np.hstack((X,v.reshape(-1,1))) # 每一个v其实是正向化后的一个指标的所有值，所以将其正向化后水平拼接得到的一行就是一个个体所有指标的集合
print(f"统一后的矩阵为{X}")


统一后的矩阵为[[0.03571429 0.08045977 0.         0.        ]
 [0.02380952 0.04597701 0.14666667 0.5       ]
 [0.         0.         0.24       1.        ]]


# 对正向化结果进行标准化

In [17]:
X=X.astype('float')
for j in range(m):
    X[:,j]=X[:,j]/np.sqrt(np.sum(X[:,j]**2))
print(f"标准化后的矩阵为{X}")

标准化后的矩阵为[[0.83205029 0.86824314 0.         0.        ]
 [0.5547002  0.49613894 0.52145001 0.4472136 ]
 [0.         0.         0.85328183 0.89442719]]


## 最大最小距离计算

In [18]:
x_max=np.max(X,axis=0)
x_min=np.min(X,axis=0)
d_z=np.sqrt(np.sum(np.square((X-np.tile(x_max,(n,1)))),axis=1))
d_f=np.sqrt(np.sum(np.square((X-np.tile(x_min,(n,1)))),axis=1))
print(f"每个指标的最大值{x_max}")
print(f"每个指标的最小值{x_min}")
print(f"the vector of d+ is {d_z}")
print(f"the vector of d- is {d_f}")

每个指标的最大值[0.83205029 0.86824314 0.85328183 0.89442719]
每个指标的最小值[0. 0. 0. 0.]
the vector of d+ is [1.23615933 0.7249117  1.20256137]
the vector of d- is [1.20256137 1.01279626 1.23615933]


## 计算参评对象得分

In [19]:
s=d_f/(d_z+d_f)
Score=100*s/sum(s)
for i in range(len(Score)):
    print(f"the {i+1}th standerm in percentage is {Score[i]}%")

the 1th standerm in percentage is 31.15370184148252%
the 2th standerm in percentage is 36.8222034470751%
the 3th standerm in percentage is 32.02409471144237%
