# PCA
PCA的主要目标是减小特征维度，主要方法为：  
- 换特征
- 减少特征

通过旋转坐标轴将高维空间的原始样本点投影到低维空间，减少维度特征，达到降维的目的

探究棉花单产和五个指标的关系
年份  单产  种子费  化肥费   农药费  机械费  灌溉费
1990 1017  106.05 495.15  305.1  45.9   56.1
...

In [1]:
import numpy as np
# 构造数据
X=np.random.randint(10,2000,size=[18,6])
X

array([[ 629, 1019,  464, 1790, 1761, 1008],
       [1806,  924,  744, 1862, 1047, 1526],
       [1429, 1655,  928,  820, 1199, 1683],
       [ 109,  192,  909,  159,  648, 1680],
       [ 388, 1775, 1009,   22, 1397, 1844],
       [1153, 1301, 1390, 1172, 1542,  393],
       [1714, 1819,  948,  578, 1139, 1238],
       [1661,  795,  720,  653,  837, 1787],
       [ 799, 1045,  510, 1533,  117,  583],
       [ 414,  298, 1787,  269,  299, 1657],
       [1951, 1153, 1112,  925,  104,  293],
       [ 918,  110, 1848,  534,  497, 1388],
       [ 729, 1065,  566,  410,  517, 1090],
       [1105,  308,  536,  306,  826,  617],
       [ 642, 1643, 1775, 1321, 1750,  999],
       [1337,  559, 1674,  425,  329, 1808],
       [ 230,  583, 1864,  923,  221,  167],
       [  64,  728, 1544,   41, 1868,  993]])

In [2]:
from scipy import linalg

In [3]:
X_standardized=(X - np.mean(X,axis=0))/np.std(X,ddof=1,axis=0)
# ddof即为计算总体或样本标准差，ddof=0表示计算总体标准差 最终除以n，ddof=1计算样本标准差，除以n-1
X_standardized

array([[-0.53154224,  0.13919748, -1.30918796,  1.78613546,  1.45825776,
        -0.25972418],
       [ 1.42489521, -0.03454536, -0.7582271 ,  1.91141725,  0.25687771,
         0.66811807],
       [ 0.79823682,  1.30236003, -0.3961671 ,  0.0983114 ,  0.51263369,
         0.94933667],
       [-1.39589864, -1.37327962, -0.43355373, -1.05184499, -0.41448172,
         0.94396306],
       [-0.93213819,  1.52182467, -0.23678199, -1.29022839,  0.8457895 ,
         1.23772007],
       [ 0.33946304,  0.65493937,  0.51291833,  0.71080013,  1.08976724,
        -1.36131295],
       [ 1.27197061,  1.60229503, -0.35681275, -0.3227746 ,  0.41167738,
         0.15225211],
       [ 1.18387275, -0.27046984, -0.80545231, -0.19227274, -0.09646936,
         1.1356216 ],
       [-0.24896419,  0.18674815, -1.21867297,  1.33894909, -1.30794504,
        -1.02098472],
       [-0.88892037, -1.1794192 ,  1.29410213, -0.86044227, -1.00171091,
         0.90276543],
       [ 1.66591766,  0.38426632, -0.0341071 ,  0.

In [5]:
R=np.cov(X_standardized.T)
R

array([[ 1.        ,  0.29119241, -0.28622956,  0.33572547, -0.15277613,
         0.0316257 ],
       [ 0.29119241,  1.        , -0.21563076,  0.26629865,  0.48040982,
        -0.02889035],
       [-0.28622956, -0.21563076,  1.        , -0.24483238, -0.06432672,
        -0.02858557],
       [ 0.33572547,  0.26629865, -0.24483238,  1.        ,  0.1305815 ,
        -0.34812166],
       [-0.15277613,  0.48040982, -0.06432672,  0.1305815 ,  1.        ,
         0.10607011],
       [ 0.0316257 , -0.02889035, -0.02858557, -0.34812166,  0.10607011,
         1.        ]])

In [11]:
#计算特征值特征向量
val,vec=linalg.eigh(R) # 该函数默认给出升序
print(val)
print(vec)
val=val[::-1]
vec=vec[:,::-1]
print(val)
print(vec)

[0.31383199 0.54005196 0.74639068 1.13881017 1.33593685 1.92497835]
[[ 0.49573977 -0.04878967  0.49946107  0.46732321 -0.31922365  0.42673829]
 [-0.50567786 -0.49005784  0.28943373 -0.05988326  0.36584986  0.5319109 ]
 [-0.02096788  0.16580031  0.80428672 -0.38991251  0.08518918 -0.40731377]
 [-0.30788096  0.68972019  0.00573336 -0.27909615 -0.29754845  0.51286719]
 [ 0.56566677  0.21819217 -0.09125129 -0.27964363  0.67980867  0.28938918]
 [-0.28865682  0.45458923  0.10737764  0.68548962  0.45422244 -0.14927109]]
[1.92497835 1.33593685 1.13881017 0.74639068 0.54005196 0.31383199]
[[ 0.42673829 -0.31922365  0.46732321  0.49946107 -0.04878967  0.49573977]
 [ 0.5319109   0.36584986 -0.05988326  0.28943373 -0.49005784 -0.50567786]
 [-0.40731377  0.08518918 -0.38991251  0.80428672  0.16580031 -0.02096788]
 [ 0.51286719 -0.29754845 -0.27909615  0.00573336  0.68972019 -0.30788096]
 [ 0.28938918  0.67980867 -0.27964363 -0.09125129  0.21819217  0.56566677]
 [-0.14927109  0.45422244  0.68548962 

In [14]:
contribute_value=val/sum(val) # 计算出每个特征值对应的贡献率
cum_contribute_value=np.cumsum(contribute_value) # 计算出累计贡献率
contribute_value,cum_contribute_value

(array([0.32082972, 0.22265614, 0.18980169, 0.12439845, 0.09000866,
        0.05230533]),
 array([0.32082972, 0.54348587, 0.73328756, 0.85768601, 0.94769467,
        1.        ]))

可以看到，在第四个累计贡献率处达到了80%以上
则可以将最初六个相关性转换为上述对应四个特征向量的线性组合